# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-09 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasrecall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gashistory',
            name='gas_amount',
            field=models.FloatField(default=0, verbose_name='Gas Amount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gashistory',
            name='paid_amount',
            field=models.FloatField(default=0, verbose_name='Paid Amount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gashistory',
            name='taco_meter',
            field=models.IntegerField(default=0, verbose_name='Tacometer'),
            preserve_default=False,
        ),
    ]
